services:
  web:
    build:
      context: .
    ports:
      - "8082:8082"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
      - PORT=8082
      - HOSTNAME=0.0.0.0
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
